version: 2
jobs:
  check:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "kappuccino/build.gradle" }}

      - run:
          name: Assemble
          command: ./gradlew clean app:googleServicesDecrypt assembleDebug
      - run:
          name: Linters
          command: ./gradlew lint ktlint
      - run: # JVM
          name: Tests - Local
          command: ./gradlew cleanTest test

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "kappuccino/build.gradle" }}

      - store_artifacts:
          path: ./app/build/reports
          destination: app-reports
      - store_artifacts:
          path: ./explorer/build/reports
          destination: explorer-reports
      - store_artifacts:
          path: ./server-ktor/build/reports
          destination: server-reports

workflows:
  version: 2
  workflow:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - develop
    jobs:
      - check